---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: src/pages
  label: Pages
  create: documents
  match: "**/*.md"
- type: directory
  path: src/posts
  label: Posts
  create: documents
  match: "**/*.md"
- type: directory
  path: src/components
  label: Components
  create: all
  match: "**/*.js"
  new_doc_ext: js
- type: directory
  path: src/templates
  label: Templates
  create: all
  match: "**/*.js"
  new_doc_ext: js
- type: directory
  path: src/styles
  label: Styles
  create: all
  match: "**/*.css"
  new_doc_ext: css
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
build:
  preview_output_directory: public
  install_dependencies_command: yarn install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn run develop
