---
new_page_extension: md
auto_deploy: false
admin_path: static/admin
webhook_url: https://webhook.gatsbyjs.com/hooks/data_source/acf7b49d-acbc-495f-bb97-382e23a0a519
sections:
- type: directory
  path: src/pages
  label: Pages
  create: documents
  match: "**/*.md"
- type: directory
  path: src/posts
  label: Posts
  create: all
  match: "**/*.md"
  templates:
  - post
- type: directory
  path: src/projects
  label: Projects
  create: all
  match: "**/*.yml"
  new_doc_ext: yml
  templates:
  - project
upload_dir: src/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:filename:"
build:
  preview_output_directory: public
  install_dependencies_command: yarn install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn forestry:preview
