---
label: Project
hide_body: true
fields:
- type: text
  name: title
  label: title
  config:
    required: true
- type: text
  name: subtitle
  label: subtitle
  config:
    required: true
- type: textarea
  name: why
  label: why
  config:
    required: true
- type: textarea
  name: what
  label: what
  config:
    required: true
- name: status
  type: select
  default: prototype
  config:
    required: true
    options:
    - production
    - preview
    - prototype
    source:
      type: simple
      section: 
      file: 
      path: 
  label: status
- name: role
  type: select
  default: contributor
  config:
    required: true
    options:
    - lead maintainer
    - maintainer
    - contributor
    source:
      type: simple
      section: 
      file: 
      path: 
  label: role
- type: text
  name: url
  label: url
  config:
    required: true
- type: number
  name: priority
  label: priority
  config:
    required: true
  default: 0
- type: field_group_list
  name: preprints
  label: preprints
  fields:
  - type: text
    name: description
    label: description
  - type: text
    name: server
    label: server
    config:
      required: true
  - type: text
    name: date
    label: date
    config:
      required: true
  - type: text
    name: url
    label: url
    config:
      required: true
- name: papers
  type: field_group_list
  fields:
  - name: description
    type: text
    config:
      required: false
    label: description
  - name: journal
    type: text
    config:
      required: true
    label: journal
  - name: date
    type: text
    config:
      required: true
    label: date
  - name: url
    type: text
    config:
      required: true
    label: url
  config:
    min: 
    max: 
    labelField: 
  label: papers
- name: websites
  type: field_group_list
  fields:
  - name: name
    type: text
    config:
      required: true
    label: name
    default: main
  - name: url
    type: text
    config:
      required: true
    label: url
  config:
    min: 
    max: 
    labelField: 
  label: websites
